create table user_details (
        dob date,
        id bigint generated by default as identity,
        email varchar(255) unique,
        firstname varchar(255) not null,
        gender varchar(255) not null,
        lastname varchar(255),
        password varchar(255) not null,
        phone varchar(255) unique,
        user_id varchar(255) not null unique,
        primary key (id)
)